model:
  pretrained_model_path: "Qwen2.5-3B-Instruct"
  device: "cuda"
  dtype: "bfloat16"



training:
  random_seed: 42
  max_prompt_len: 256
  max_gen_len: 1024
  batch_size: 256
  num_questions_per_batch: 32
  micro_batch_size: 4
  learning_rate: 2.0e-6   
  weight_decay: 0.0
  max_grad_norm: 1.0
  betas: [0.9, 0.999]
  memory_efficient_adamw: false
  
  ckpt_dir: "ckpt/3b_kl"
  log_dir: "logs"
  ckpt_save_interval: 20
  eval_interval: 10
  skip_unfinished_episodes: false
  loss_type: "kl"
  
  beta: 0.2         
  kl_target: 0.01

  ot_target: 0.05
  ot_window: 16