model:
  pretrained_model_path: "Qwen/Qwen2.5-0.5B-Instruct"
  device: "cuda"
  dtype: "bfloat16"

training:
  random_seed: 1337
  max_prompt_len: 256
  max_gen_len: 1024
  batch_size: 256
  num_questions_per_batch: 32
  # Number of examples per gradient accumulation step
  micro_batch_size: 4
  max_grad_norm: 1.0
  learning_rate: 1.0e-6
  weight_decay: 0.0
  betas: [0.9, 0.999]
  ckpt_dir: "ckpt/3b_ot"
  log_dir: "logs"
  skip_unfinished_episodes: false
  ckpt_save_interval: 20
  eval_interval: 10
  memory_efficient_adamw: false
  loss_type: "ot"   # 选项: "ot" 或 "kl"
  beta: 0.1        # 惩罚系数 (对应 lambda_ot 或 lambda_kl)
  ot_target: 0.05   # OT Trust Region 半径
  ot_window: 16     # 局部窗口大小
  kl_target: 0.0    # KL Trust Region 半径 (通常为0)